apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: crossplane-test-config
spec:
  crossplane:
    version: '>=v1.9.1'
  dependsOn:
  - provider: crossplane/provider-aws
    version: '>=v0.31.0'
